FROM node:24-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --production

COPY . .

RUN apk add --no-cache ttf-dejavu

RUN npm install @nestjs/cli

RUN npm run build

CMD [ "npm", "run", "start:prod" ]